### PR TITLE
 Using CHECK with bitfield fails to compile #786 

### PR DESCRIPTION
**Pull request by navinp0304**
Change universal reference to rvalue reference by adding const

### CODE REVIEW

**Comment by navinp0304** [comment]
@onqtam can you please merge this ?

**Comment by onqtam** [comment]
This part of the code is the most tricky of all... Just did a git blame and it seems that this commit was the last modification for them: ce13bc44b99c87e918b98bdadb17008d2dd54d55

Your proposed changes are not a direct revert of that commit - there are some differences.

I'm no longer in a position to evaluate such changes - I haven't touched C++ in 2-3 years in any meaningful way. I've moved on completely.

This project is looking for maintainers again - as noted here: https://github.com/doctest/doctest/issues/554#issuecomment-1740568920

The amount of work is very little - I'd argue that someone capable should be able to spend no more than 1-2 hours a month to keep up with PRs & issues - there aren't that many of them.

I can't merge this PR at this time - I can't evaluate it properly and am not sure if there are sufficient tests to catch any regressions.

**Comment by navinp0304** [comment]
@Saalvage can you please review and merge this ?

**Comment by onqtam** [comment]
@navinp0304 if you manage to reproduce the problems from before commit ce13bc44b99c87e918b98bdadb17008d2dd54d55 (which it was aimed at addressing) and then confirm that they're no longer present after your current patch and just say so - I'll merge this.

**Comment by navinp0304** [comment]
https://github.com/doctest/doctest/issues/630 is fixed by the current merge. I tried running https://godbolt.org/z/5Y87aMW8W and it passed.

**Comment by onqtam** [comment]
Sorry for taking so long - I wanted to look at the build failures and deal with those first, but I can't get myself to do even that - so I'm merging this as it is.

**Pull request merged**
