### PR TITLE
Support pretty printing of container based on heuristics

### PR DESCRIPTION
**Pull request by YarikTH**
## Description

There are a lot of complaints about the fact, that vector values and other containers output as "{?}" because their stringification is not supported.

I think that it should not be much hard to support standard containers (or at least most of them) without including nothing but type_traits.

```c++
template<typename T, typename = void> struct has_begin_end_overloads : std::false_type {};
template<typename T>                  struct has_begin_end_overloads<T, std::void_t<
    decltype( std::begin( std::declval<T>() ) != std::end( std::declval<T>() ) )
    >> : std::true_type {};
template<typename T> constexpr bool has_begin_end_overloads_v = has_begin_end_overloads<T>::value;

template<typename T, typename = void> struct has_mapped_type : std::false_type {};
template<typename T>                  struct has_mapped_type<T, std::void_t<
    typename T::mapped_type
    >> : std::true_type {};
template<typename T> constexpr bool has_mapped_type_v = has_mapped_type<T>::value;

template<typename T> constexpr bool is_element_container_v = has_begin_end_overloads_v<remove_all_t<T>> && !has_mapped_type_v<remove_all_t<T>>;
// output as [X, Y, Z]
// detects vector, list, deque, set etc. works even with old good C arrays

template<typename T> constexpr bool is_key_value_container_v = has_begin_end_overloads_v<remove_all_t<T>> && has_mapped_type_v<remove_all_t<T>>;
// output as {X: XX, Y: YY, Z: ZZ}
// works with map and unordered_map
```

I have written such code for my closed sourced project and it took less than 300 LOC to support stringification of pairs, tuples, pointers, etc. Unfortunately, it is ported to C++17 but with some effort, code can be adapted to C++11.

I'm sure that this stringification would be a great optional feature (enabled by default or not) and doesn't bloat the code at all. But benchmarks should measure it better as soon there is something to measure.

I often use doctest here and there and I'm bored to copy-paste vertor stringification again and again and again. I prefer it to be in the doctest, even in a disabled state by default.

## GitHub Issues

#121, #170, #192, #248

### CODE REVIEW

**Comment by YarikTH** [comment]
Looked through https://github.com/Saalvage/doctest/blob/dev/doctest/extensions/stl_stringifier.h

Looks like a lot of well-adjusted work to process all the possible things std throws at you. A generalized approach, unfortunately, couldn't cover all the listed classes, but I think it covers at least half of them. Others are more rarely used anyway.

**Comment by Saalvage** [comment]
`DOCTEST_CONFIG_INCLUDE_TYPE_TRAITS` is already a config option!

**Comment by YarikTH** [comment]
Waiting for #585. There is no point in adding additional stringification, while the current one is broken a little.

Some little preparation is done in godbolt https://godbolt.org/z/bKhsfcxns

**Comment by elad-eyal-ns** [comment]
#585 is merged - this ticket should be re-opened?

**Pull request closed without merging**
